# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build my-ecommerce-app`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t my-ecommerce-app`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system my-ecommerce-app && \
          adduser --system -G my-ecommerce-app my-ecommerce-app

COPY dist/my-ecommerce-app my-ecommerce-app
RUN chown -R my-ecommerce-app:my-ecommerce-app .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix my-ecommerce-app --omit=dev -f install

CMD [ "node", "my-ecommerce-app" ]
